# default
server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active:
      - local
    group:
      local:
        - db-local
      prod:
        - db-prod
    include:
      - db

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: refresh

message: "default message"