# default
server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active:
      - local
    group:
      local:
        - db-local
      prod:
        - db-prod
    include:
      - db
      - infra

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

delivery:
  max-waiting-time-minutes: ${DELIVERY_MAX_WAITING_TIME_MINUTES}