# default
server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active:
      - local
    group:
      local:
        - db-local
      prod:
        - db-prod
    include:
      - db

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

api:
  key:
    ${REST_API_KEY}